In [6]:
import numpy as np

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.random.randn(5, 2)

array([[ 0.59369436,  1.50046849],
       [ 0.6523459 , -0.16736199],
       [ 0.10915779, -1.77921025],
       [ 2.70134004, -0.52873854],
       [-0.0419207 ,  1.37581231]])

In [10]:
np.random.rand(5, 2)

array([[0.78208731, 0.26148448],
       [0.0762249 , 0.38295273],
       [0.64799518, 0.03947801],
       [0.08941252, 0.36649198],
       [0.08495819, 0.32821839]])

In [11]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[76, 14],
       [94,  4],
       [22, 62],
       [74, 41],
       [40, 64]])

In [13]:
np.random.seed(2)

In [14]:
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [8]:
u=np.array([2,4,5,6])

In [9]:
v=np.array([1,3,2,0])

In [10]:
v+u

array([3, 7, 7, 6])

In [11]:
def vector_vector_multiplication(u, v):
    assert u.shape[0]==v.shape[0]

    n=u.shape[0]
    
    result=0.0
    
    for i in range(n):
        result = result + u[i]*v[i]

    return result

In [12]:
vector_vector_multiplication(v,u)

np.float64(24.0)

In [13]:
v.dot(u)

np.int64(24)

In [15]:
U=np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1],])

In [17]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [18]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1]==v.shape[0]

    num_rows=U.shape[0]
    
    result=np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)

    return result

In [19]:
matrix_vector_multiplication(U,v)

array([24.,  9., 10.])

In [20]:
U.dot(v)

array([24,  9, 10])

In [22]:
V=np.array([[1,1,2],[0,0.5,1],[0,2,1],[2,1,0]])

In [23]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1]==V.shape[0]

    num_rows=U.shape[0]
    num_cols=V.shape[1]
    
    result=np.zeros((num_rows,num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        
        Uvi = matrix_vector_multiplication(U,vi)

        result[:,i] = Uvi

    return result

In [24]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [25]:
matrix_matrix_multiplication(V, U)

array([[ 9. ,  8. , 10. , 10. ],
       [ 3.5,  2. ,  2.5,  2. ],
       [ 5. ,  5. ,  4. ,  5. ],
       [ 5. , 10. , 11. , 14. ]])